default_connection_name = "myconnection"
[connections]
[connections.myconnection]
user = ""

#default_connection_name = "my_test_connection" 
#[connections]
#[connections.my_test_connection]
#account = "onlwzlj-dev_account"
#user = "IQCHY500"
#password = "Chy@7735411064"
#database = "DEMO_DB"
#schema = "PUBLIC"